# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Text-I18N
version:      0.02
version_from: I18N.pm
installdirs:  site
requires:
    I18N::LangTags:                0
    I18N::LangTags::Detect:        0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
